autodo-app/autodo

- lib/blocs/refueling.dart
- lib/blocs/todo.dart
- lib/blocs/userauth.dart
- lib/maintenance/history.dart
- lib/maintenance/todocard.dart
- lib/refueling/history.dart
- lib/screens/editrepeats.dart
- lib/screens/homescreen.dart
- lib/screens/statistics.dart
- lib/theme.dart
> Better UX for the homescreen

- lib/app.dart
- lib/blocs/firestore.dart
- lib/blocs/markdown.dart
- lib/blocs/refueling.dart
- lib/blocs/repeating.dart
- lib/blocs/todo.dart
- lib/blocs/userauth.dart
- lib/refueling/history.dart
- lib/screens/homescreen.dart
- lib/screens/loadingpage.dart
- lib/screens/logins.dart
- lib/screens/newusersetup/latestcompleted.dart
- lib/screens/newusersetup/setrepeats.dart
The sign up process was wonky and as a result, new users would not be able to see the pre-filled todo items until they restarted the app. This change makes it so that the app startup process runs properly when a new user logs in.
Closes #68.
> Fix firebase sync on sign up

- lib/blocs/cars.dart
- lib/blocs/refueling.dart
- lib/items/car.dart
- lib/screens/createrefueling.dart
> Update Car's mileage through a new refueling

- lib/blocs/todo.dart
- lib/maintenance/todocard.dart
> Fixed todo editing issue with preface text

- lib/screens/createmaintenancetodo.dart
- lib/theme.dart
> Fix theming in new maintenance todo screen

- lib/blocs/notifications.dart
- lib/blocs/subcomponents/base.dart
- lib/items/maintenancetodo.dart
- lib/maintenance/todocard.dart
Adding a new todo item threw a number of exceptions from various places. There is still a bit more work to do with #96 but this makes sure that the app doesn't break at least.
> Fix exceptions thrown by creating new todo items

- lib/screens/createmaintenancetodo.dart
- lib/screens/createrefueling.dart
- lib/util.dart
> Block saving of required fields until they have content

- lib/blocs/repeating.dart
- lib/blocs/subcomponents/base.dart
- lib/blocs/todo.dart
- lib/screens/editrepeats.dart
- lib/screens/homescreen.dart
> Update todo items associated with a repeat when interval changes

- lib/blocs/repeating.dart
- lib/blocs/todo.dart
- lib/items/maintenancetodo.dart
I broke some things with #102 and this undoes the todo duplication and improper math that happened with those changes.
Closes #103
> Fixed issues with editing repeating tasks

- lib/blocs/repeating.dart
- lib/blocs/subcomponents/base.dart
- lib/items/repeat.dart
- lib/items/repeateditor.dart
- lib/screens/createitems/createrepeat.dart
Deleting a repeating task removes it from the list of repeats and deletes its associated ToDo item. Hitting the "undo" button on the resulting snackbar will restore both the repeat and its ToDo(s).
Closes #90.
> Proper Repeating Task deletion

- lib/blocs/init.dart
- lib/blocs/repeating.dart
- lib/blocs/subcomponents/firestore.dart
- lib/blocs/subcomponents/subcomponents.dart
- lib/blocs/userauth.dart
- lib/screens/homescreen.dart
- lib/screens/settings.dart
- lib/sharedmodels/navdrawer.dart
Threw it in the Settings menu for now, I'm not entirely sure where it ought to belong long-term. Settings should be a fine place for now.
Closes #84.
> Delete Account button

- lib/items/maintenancetodo.dart
- lib/screens/createitems/createmaintenancetodo.dart
Pretty self-explanatory. Found a method for dynamically sizing the list of filters though which is neat, this makes #73 a fairly straightforward task.
Closes #96.
> Add cars field to the todo create screen

- lib/maintenance/todocard.dart
It's not a progressive shading, instead it separates items into three buckets: upcoming, due soon, and past due. Shading corresponds to each of these three states.
Closes #81.
> Added 3 stage shading for soonest todos

- lib/blocs/cars.dart
- lib/blocs/refueling.dart
- lib/items/car.dart
- lib/items/refueling.dart
- lib/refueling/refuelingcard.dart
- lib/util.dart
> Conditionally shade the fuel efficiency stat on refueling cards

- lib/blocs/cars.dart
- lib/blocs/refueling.dart
- lib/blocs/todo.dart
- lib/items/car.dart
- lib/items/maintenancetodo.dart
- lib/items/refueling.dart
- lib/maintenance/todocard.dart
- lib/screens/createitems/createmaintenancetodo.dart
- lib/screens/newusersetup/mileage.dart
- lib/util.dart
Estimated Due Dates are created for ToDo items from their Due Mileage and the rate at which the driver puts miles on their vehicle. This is mainly to provide a basis for scheduling notifications for ToDo items.
Closes #36.
> Estimate ToDo Due Dates from their Due Mileage

- lib/items/car.dart
> Fixed issue with serializing car data

- lib/blocs/cars.dart
- lib/blocs/refueling.dart
- lib/blocs/subcomponents/base.dart
- lib/blocs/todo.dart
- lib/items/car.dart
- lib/refueling/refuelingcard.dart
- lib/screens/createitems/createrefueling.dart
> Fix misc errors related to 0.1.3 smoke test

- .github/workflows/main.yml
- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- pubspec.yaml
- test/dummy_test.dart
Still working on what the best setup would be for CD, but CI is working and builds run fine.
Closes #65
> Set up CI workflow with Github Actions

- lib/screens/createitems/createmaintenancetodo.dart
- lib/screens/createitems/createrefueling.dart
- lib/screens/createitems/createrepeat.dart
- lib/screens/logins.dart
- lib/screens/newusersetup/latestcompleted.dart
- lib/screens/newusersetup/mileage.dart
- lib/screens/newusersetup/setrepeats.dart
- lib/util.dart
Currently in new item and new user screens.
Closes #48
> Add 'Next' and 'Done' actions where appropriate to text input fields

- lib/blocs/repeating.dart
- lib/screens/newusersetup/latestcompleted.dart
- lib/screens/newusersetup/mileage.dart
- lib/screens/newusersetup/setrepeats.dart
- lib/util.dart
> Clean up validation process for new user setup

- lib/blocs/repeating.dart
- lib/screens/createitems/createrefueling.dart
- lib/sharedmodels/autocompletefield.dart
> Fix issue with back button in forms with autocompletefield

- lib/screens/createitems/createmaintenancetodo.dart
- lib/screens/createitems/createrefueling.dart
Kind of a hack but it works.
Closes #98.
> Validation on autocomplete fields

- .github/workflows/main.yml
- .gitignore
- lib/main.dart
- lib/secret_loader.dart
- pubspec.yaml
> Add support for reporting errors to sentry

- .github/workflows/main.yml
- .github/workflows/test.yml
> Split tests and build into two github actions

- lib/blocs/src/cars/bloc.dart
- lib/blocs/src/filtered_refuelings/bloc.dart
- lib/blocs/src/filtered_refuelings/event.dart
- lib/blocs/src/filtered_refuelings/state.dart
- lib/blocs/src/notifications/bloc.dart
- lib/blocs/src/refuelings/bloc.dart
- lib/blocs/src/repeating/bloc.dart
- lib/blocs/src/todos/bloc.dart
- lib/main.dart
- lib/screens/home/provider.dart
- test/blocs/cars/cars_bloc_test.dart
- test/blocs/filtered_refuelings/filtered_refuelings_bloc_test.dart
- test/blocs/filtered_refuelings/filtered_refuelings_event_test.dart
- test/blocs/filtered_refuelings/filtered_refuelings_state_test.dart
- test/blocs/notifications/notifications_bloc_test.dart
- test/blocs/refuelings/refuelings_bloc_test.dart
- test/blocs/repeating/repeats_bloc_test.dart
- test/blocs/todos/todos_bloc_test.dart
- test/screens/home/views/refuelings_test.dart
- test/util_test.dart
There had been a number of missing bloc providers and circular bloc dependencies before, this change creates a working, albeit deep, structure of blocs that runs properly.
> Rearrange bloc hierarchy to run properly

- lib/screens/home/widgets/todo_card.dart
> reduce font size of last completed text

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
- ios/Runner/GeneratedPluginRegistrant.m
- lib/screens/home/screen.dart
- lib/widgets/src/banner_ad.dart
- lib/widgets/widgets.dart
- pubspec.yaml
- test/test.db
- test/widgets/action_button_test.dart
- test/widgets/banner_ad_test.dart
- test/widgets/snackbars_test.dart
> Add ads to home and add/edit screens

- android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
- ios/Runner/GeneratedPluginRegistrant.m
- lib/blocs/blocs.dart
- lib/blocs/src/paid_version/barrel.dart
- lib/blocs/src/paid_version/bloc.dart
- lib/blocs/src/paid_version/event.dart
- lib/blocs/src/paid_version/state.dart
- lib/blocs/src/todos/bloc.dart
- lib/main.dart
- lib/repositories/src/data_repository.dart
- lib/repositories/src/firebase_data_repository.dart
- lib/repositories/src/sembast_data_repository.dart
- lib/screens/home/screen.dart
- lib/widgets/src/navdrawer.dart
- lib/widgets/src/upgrade_dialog.dart
- pubspec.yaml
Removes the default behavior of showing banner ads on the home screen.
Closes #180
> Add the ability to purchase an ad-free autodo

- lib/screens/welcome/views/login/form.dart
- lib/screens/welcome/views/signup/form.dart
> Show signin snackbar until auth is complete

- lib/widgets/src/navdrawer.dart
> remove dead link to repeats edit screen

- lib/blocs/src/repeating/bloc.dart
- lib/blocs/src/repeating/state.dart
- lib/screens/welcome/views/new_user_setup/mileage.dart
> Fix overwritten data when adding multiple cars in setup screens

- .gitignore
- lib/localization.dart
- lib/screens/home/widgets/todo_card.dart
> force "completed" preface for completed todos

- lib/screens/add_edit/refueling.dart
- lib/screens/home/screen.dart
> Fix bugs in Refueling add/edit UX

- lib/screens/home/screen.dart
- lib/screens/welcome/views/signup/form.dart
> email verification moves on properly now

- lib/main.dart
- lib/screens/welcome/views/login/form.dart
- lib/screens/welcome/views/signup/form.dart
- lib/screens/welcome/views/signup/screen.dart
- lib/screens/welcome/widgets/buttons/login_to_signup.dart
- lib/screens/welcome/widgets/buttons/signup_to_login.dart
> allow for switching back and forth between login/signup

- lib/blocs/src/auth/login/bloc.dart
- lib/blocs/src/auth/login/state.dart
- lib/screens/welcome/widgets/buttons/password_reset.dart
> password reset works again

- .github/workflows/main.yml
> support automated ios builds

- .github/workflows/main.yml
- lib/blocs/src/paid_version/bloc.dart
- lib/main.dart
- lib/screens/home/screen.dart
- pubspec.yaml
- test/screens/home/screen_test.dart
- test/test.db
> use own fork of firebase_admob to clear ads

- lib/screens/home/views/todos.dart
> giving each card a unique key prevents error msg

- .github/workflows/main.yml
- lib/blocs/src/cars/bloc.dart
- lib/blocs/src/filtered_todos/bloc.dart
- lib/blocs/src/refuelings/bloc.dart
- lib/blocs/src/repeating/bloc.dart
- lib/blocs/src/todos/bloc.dart
- lib/delegate.dart
- lib/main.dart
- lib/repositories/src/firebase_data_repository.dart
- lib/screens/add_edit/todo.dart
- lib/screens/home/screen.dart
- lib/screens/home/views/refuelings.dart
- lib/screens/home/views/todos.dart
- lib/screens/home/widgets/refueling_card.dart
- test/blocs/todos/todos_bloc_test.dart
- test/screens/add_edit/todo_test.dart
- test/screens/home/screen_test.dart
- test/test.db
> Fix issue with firestore items not displaying on launch

- assets/intl/strings.json
GitHub Merge button screwed up the English json file, strange.
> Fix strange GitHub merge issue

- .github/workflows/analyze.yml
- .github/workflows/main.yml
- pubspec.yaml
> Add analysis action

- lib/flavor.dart
- lib/generated/localization.dart
- lib/main.dart
- lib/screens/home/screen.dart
- lib/widgets/src/navdrawer.dart
- pubspec.lock
> 287 deactivate ads

- lib/blocs/src/cars/bloc.dart
- lib/blocs/src/database/bloc.dart
- lib/blocs/src/todos/bloc.dart
- lib/generated/pubspec.dart
- lib/main.dart
- lib/models/src/refueling.dart
- lib/models/src/repeat_interval.dart
- lib/repositories/src/data_repository.dart
- lib/repositories/src/firebase_data_repository.dart
- lib/repositories/src/sembast_data_repository.dart
- lib/repositories/src/sembast_write_batch.dart
- test/account_setup_test.dart
- test/blocs/database/database_bloc_test.dart
- test/blocs/todos/todos_bloc_test.dart
- test/models/repeat_interval_test.dart
- test/repositories/firebase_data_repositories_test.dart
- test/repositories/sembast_data_repository_test.dart
- test/repositories/sembast_write_batch_test.dart
- test/screens/add_edit/todo_test.dart
- test_driver/app.dart
- test_driver/app_test.dart
- test_driver/tests/refuelings.dart
> Fix Firebase migration

- lib/screens/welcome/views/new_user_setup/latestcompleted.dart
- lib/screens/welcome/views/new_user_setup/setrepeats.dart
> Fix the "skip" button in the new user screens

- ios/Podfile.lock
- lib/flavor.dart
- lib/generated/pubspec.dart
- lib/main.dart
- pubspec.lock
- pubspec.yaml
> 263 add basic analytics to the app

- assets/intl/strings.json
- lib/generated/localization.dart
- lib/generated/pubspec.dart
- lib/screens/add_edit/car.dart
- lib/screens/add_edit/todo.dart
- lib/screens/home/widgets/car_card.dart
- lib/screens/settings/screen.dart
- pubspec.lock
- pubspec.yaml
> Polishing up the Garage Screen

- lib/blocs/src/todos/bloc.dart
- lib/blocs/src/todos/event.dart
- lib/screens/home/screen.dart
- lib/screens/home/widgets/new_car_card.dart
- lib/screens/welcome/views/new_user_setup/mileage.dart
- test/blocs/todos/todos_bloc_test.dart
Depends on #303 going in first
Closes #306
> Create sets of default todos for each distance unit type

- lib/blocs/src/database/bloc.dart
- lib/flavor.dart
- lib/repositories/src/data_repository.dart
- lib/repositories/src/demo_data_repository.dart
- lib/repositories/src/local_storage_repository.dart
"Try without an account" in debug mode will be filled with predefined data.
This allows checking that the graphics are correctly computed and we can also use it, maybe with a different set to generate the app' screenshots.
http://www.carponents.com/content/23-facts-about-christine-cinemas-most-haunted-car-the-1958-plymouth-fury-244
> Add a demo data generator

- lib/generated/pubspec.dart
- lib/main.dart
- lib/screens/settings/screen.dart
- lib/units/currency.dart
- lib/units/distance.dart
- lib/units/efficiency.dart
- lib/units/volume.dart
- pubspec.lock
- pubspec.yaml
- test/account_setup_test.dart
- test/models/efficiency_stats_test.dart
- test/screens/add_edit/car_test.dart
- test/screens/add_edit/forms_test.dart
- test/screens/add_edit/refueling_test.dart
- test/screens/add_edit/todo_test.dart
- test/screens/home/screen_test.dart
- test/screens/home/views/garage_test.dart
- test/screens/home/views/refuelings_test.dart
- test/screens/home/views/stats_test.dart
- test/screens/home/views/todos_test.dart
- test/screens/home/widgets/car_card_test.dart
- test/screens/home/widgets/new_car_card_test.dart
- test/screens/home/widgets/refueling_edit_test.dart
- test/screens/home/widgets/todo_card_test.dart
- test/screens/home/widgets/todo_edit_test.dart
- test/screens/settings_test.dart
- test/screens/welcome/views/new_user_screens_test.dart
- test/widgets/upgrade_dialog_test.dart
I also published the preferences library as pref.
https://pub.dev/packages/pref
> Migrate to pref library

- assets/intl/strings.json
- lib/blocs/src/filtered_todos/bloc.dart
- lib/blocs/src/filtered_todos/state.dart
- lib/blocs/src/todos/bloc.dart
- lib/flavor.dart
- lib/generated/localization.dart
- lib/models/src/todo_due_state.dart
- lib/screens/home/views/refuelings.dart
- lib/screens/home/widgets/refueling_card.dart
- test/blocs/filtered_todos/filtered_todos_bloc_test.dart
> Fix bugs found on new account creation
